FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e55e71960269793c1ff70b8934048bfb756ec93ce57f4268c749ab3b39c26cb3

ARG REPO=https://inaccel-amazon.s3.amazonaws.com/rhel
ARG XRT=xrt_202010.2.6.0_8.3.2011-x86_64-xrt.rpm 
ARG AWS=xrt_202010.2.6.0_8.3.2011-x86_64-aws.rpm


RUN dnf repolist --disablerepo=*
RUN cat /etc/yum.repos.d/redhat.repo

RUN sleep infinity

RUN dnf makecache
RUN dnf repolist

RUN dnf -v update --allowerasing --skip-broken -y

#RUN dnf -v  -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

RUN dnf -v config-manager --set-enabled codeready-builder-for-rhel-8-x86_64-rpms || true


RUN dnf -v install -y ${REPO}/${XRT} ${REPO}/{AWS} || true


RUN sleep infinity

RUN dkms build -m xrt/2.6.0
RUN dkms install -m xrt/2.6.0


RUN systemctl enable mpd


